Resources:

  ProjectRepos:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: project-repos
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:  
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DemoSqs:
    Type: AWS::SQS::Queue
    Properties: 
      QueueName: demo-queue
      VisibilityTimeout: 180
      MessageRetentionPeriod: 900

  AsyncPythonLambdaFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: async-py-lambda-function-role
      AssumeRolePolicyDocument: 
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: s3-code-read-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 's3:ListBucket'
                  - 's3:GetObject'
                Resource:
                  - !GetAtt ProjectRepos.Arn
                  - !Join ['', [!GetAtt ProjectRepos.Arn, '/*']]
        - PolicyName: sqs-send-message-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - 'sqs:SendMessage'
                  - 'sqs:GetQueueUrl'
                Resource:
                  - !GetAtt DemoSqs.Arn
  
  AsyncPythonLambdaFunction:
    Type: AWS::Lambda::Function
    Properties: 
      FunctionName: async-py-function
      Handler: lambda_function.lambda_handler
      MemorySize: 128
      Role: !GetAtt AsyncPythonLambdaFunctionRole.Arn
      Runtime: python3.10
      Timeout: 360
      Environment:
        Variables:
          DEMO_QUEUE: !Ref DemoSqs
          REGION: us-east-1
      Code:
        S3Bucket: !Ref ProjectRepos
        S3Key: !Join ['', ['AsyncPythonLambdaFunction', '.zip']]

