name: Build and Deploy Actions
run-name: ${{ github.actor }} is building and deploying the code.
env:
  REPO_NAME: ${{ github.event.repository.name }}
on:
  push:
    paths:
      - 'lambda_function.py'
      - 'stack.yml'
      - 'stack-buckets.yml'
      - '.github/workflows/cicd-actions.yml'

jobs:

  CreateProjectReposS3Bucket:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials for Deploying
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}
      - name: Create S3Bucket AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: CreateProjectReposS3Bucket
          template: stack-buckets.yml
          capabilities: CAPABILITY_NAMED_IAM
          no-fail-on-empty-changeset: 1

  Build:
    runs-on: ubuntu-latest
    needs: CreateProjectReposS3Bucket
    outputs:
      BuildGuid: ${{ steps.step3.outputs.BuildGuid }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --target='.'
      - name: Create code build guid
        id: step3
        run: |
          echo "BuildGuid=$(date +%s)" >> "$GITHUB_OUTPUT"
      - name: Zip the code
        run: |
          zip -r "$REPO_NAME-${{ steps.step3.outputs.BuildGuid }}.zip" . -x ".github/*" ".stack.yml"
      - name: Configure AWS credentials for Uploading to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload the zip file to S3
        run: |
          aws s3 cp "$REPO_NAME-${{ steps.step3.outputs.BuildGuid }}.zip"  "s3://$REPO_NAME/${{ secrets.PROJECT_REPOS }}/"

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials for Deploying
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION}}
      - name: Deploy to AWS CloudFormation
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: ${{ github.event.repository.name }}
          template: stack.yml
          capabilities: CAPABILITY_NAMED_IAM
          parameter-overrides: "BuildGuid=${{ needs.Build.step4.outputs.BuildGuid }}"